# permissions for end users to view exportports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exportport-viewer-role
rules:
- apiGroups:
  - export-port.com.test
  resources:
  - exportports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - export-port.com.test
  resources:
  - exportports/status
  verbs:
  - get
